{
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": "moon",
  "compatibility_date": "2026-07-15",
  "observability": {
    "enabled": true
  },
  "assets": {
    "directory": "."
  },
  "compatibility_flags": [
    "nodejs_compat"
  ],
  "d1_databases": [
    {
      "binding": "DB",
      "database_name": "den",
      "database_id": "07f7ddb2-a909-43f8-bc5f-6f3a630def82"
    }
  ]
}
